#!/bin/bash



# sysinfo_page - A script to produce an system information HTML file



##### Constants



TITLE="System Information for $HOSTNAME"

RIGHT_NOW="$(date +"%x %r %Z")"

TIME_STAMP="Updated on $RIGHT_NOW by $USER"
ROOT="root"

##### Functions



system_info()
{
    echo "<h2>System Info</h2>
    <pre>"
    uname -a
    echo "</pre>"
}

free_memory()
{
    echo "<h2>Free memory</h2>
    <pre>"
    free
    echo "</pre>"
}

disk_info()
{
    echo "<h2>Disk Information</h2>
    <pre>"
    fdisk -l
    echo "</pre>"
}

show_uptime()
{
    echo "<h2>System uptime</h2>
    <pre>"
    uptime
    echo "</pre>"
}





drive_space()
{
    echo "<h2>Filesystem Space</h2>
    <pre>"
    df
    echo "</pre>"
}





home_space()
{
    echo "<h2>Home directory space by user</h2>
    <pre>
    Bytes Directory"
    du -s /home/* | sort -nr
    echo "</pre>"
}

user_info()
{
    echo "<h2>Users</h2>
    <pre>"
    for i in $(cat /etc/passwd | grep bash | cut -d ":" -f 1 ); do groups $i; done
    echo "</pre>"
}

ip_info()
{
    echo "<h2>Ip Information</h2>
    <pre>"
    hostname -I
    echo "</pre>"
}


cpu_info()
{
    echo "<h2>CPU</h2>
    <pre>"
    lshw | grep product | cut -d ":" -f 2 | head -4
    echo "</pre>"
}




##### Main


if ((EUID!=0))
then
  echo "Must Run as Root"
  exit 1
fi
cat <<- _EOF_
  <html>
  <head>
      <title>$TITLE</title>

  </head>
  <body>
      <h1>$TITLE</h1>
      <p>$TIME_STAMP</p>
      $(system_info)
      $(show_uptime)
      $(drive_space)
      $(home_space)
      $(free_memory)
      $(disk_info)
      $(user_info)
      $(ip_info)
      $(cpu_info)
  </body>
  </html>

_EOF_
